#Use official Node runtime as parent image
FROM node:latest

# Set the working directory to /app
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied

#COPY ./src/package*.json ./

#RUN npm install

# Bundle app source
#COPY ./src .

#EXPOSE 15000
#CMD ["npm", "start"]